# Generated by Django 5.2.11 on 2026-02-12 20:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Solicitante")),
                (
                    "codigo",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código do Cliente"
                    ),
                ),
                (
                    "contato",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Contato/Telefone",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Área/Talhão (ha)",
                    ),
                ),
                (
                    "municipio",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Município/UF",
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações Gerais"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário de Acesso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="AnaliseSolo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_lab",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nº Laudo"
                    ),
                ),
                (
                    "data_entrada",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Entrada",
                    ),
                ),
                (
                    "data_saida",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Saída"
                    ),
                ),
                (
                    "ph_agua",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="pH Água"
                    ),
                ),
                (
                    "ph_kcl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="pH KCl",
                    ),
                ),
                (
                    "ph_cacl2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="pH CaCl2",
                    ),
                ),
                (
                    "calcio",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Ca²+"
                    ),
                ),
                (
                    "magnesio",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Mg²+"
                    ),
                ),
                (
                    "aluminio",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Al³+"
                    ),
                ),
                (
                    "hidrogenio_aluminio",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="H+Al"
                    ),
                ),
                (
                    "fosforo_mehlich",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="P (Mehlich)"
                    ),
                ),
                (
                    "potassio",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="K (Potássio)"
                    ),
                ),
                (
                    "materia_organica",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="M.O."
                    ),
                ),
                (
                    "areia",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Areia %",
                    ),
                ),
                (
                    "argila",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Argila %",
                    ),
                ),
                (
                    "silte",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Silte %",
                    ),
                ),
                (
                    "soma_bases",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="SB",
                    ),
                ),
                (
                    "ctc_efetiva",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="t",
                    ),
                ),
                (
                    "ctc_potencial",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="T",
                    ),
                ),
                (
                    "v_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="V%",
                    ),
                ),
                (
                    "m_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="m%",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analises",
                        to="database.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análise de Solo",
                "verbose_name_plural": "Análises de Solo",
            },
        ),
    ]
