# Generated by Django 5.2.11 on 2026-02-12 21:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analisesolo",
            old_name="ctc_potencial",
            new_name="T_maiusculo",
        ),
        migrations.RenameField(
            model_name="analisesolo",
            old_name="hidrogenio_aluminio",
            new_name="h_al",
        ),
        migrations.RenameField(
            model_name="analisesolo",
            old_name="soma_bases",
            new_name="sb",
        ),
        migrations.RenameField(
            model_name="analisesolo",
            old_name="ctc_efetiva",
            new_name="t",
        ),
        migrations.RemoveField(
            model_name="analisesolo",
            name="aluminio",
        ),
        migrations.RemoveField(
            model_name="analisesolo",
            name="calcio",
        ),
        migrations.RemoveField(
            model_name="analisesolo",
            name="codigo_lab",
        ),
        migrations.RemoveField(
            model_name="analisesolo",
            name="fosforo_mehlich",
        ),
        migrations.RemoveField(
            model_name="analisesolo",
            name="m_percent",
        ),
        migrations.RemoveField(
            model_name="analisesolo",
            name="magnesio",
        ),
        migrations.RemoveField(
            model_name="analisesolo",
            name="materia_organica",
        ),
        migrations.RemoveField(
            model_name="analisesolo",
            name="potassio",
        ),
        migrations.RemoveField(
            model_name="analisesolo",
            name="v_percent",
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="V",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True, verbose_name="V"
            ),
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="al",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="Al3+"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="b",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="B"
            ),
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="c_org",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="C-org",
            ),
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="ca",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="Ca"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="ca_k",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Ca/K",
            ),
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="ca_mg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Ca/Mg",
            ),
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="cu",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="Cu"
            ),
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="fe",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="Fe"
            ),
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="k",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="K"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="m",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True, verbose_name="m"
            ),
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="mg",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="Mg2+"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="mg_k",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Mg/K",
            ),
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="mn",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="Mn"
            ),
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="mo",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="MO"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="n_lab",
            field=models.CharField(
                default=0, max_length=50, unique=True, verbose_name="N Lab"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="na",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="Na"
            ),
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="p_m",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Mehlich",
                max_digits=8,
                verbose_name="P_M",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="p_r",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Resina",
                max_digits=8,
                null=True,
                verbose_name="P_R",
            ),
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="p_rem",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="P-rem",
            ),
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="s",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="S"
            ),
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="zn",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="Zn"
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analises",
                to="database.cliente",
                verbose_name="Código cliente",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="data_entrada",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data Entrada"
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="data_saida",
            field=models.DateField(blank=True, null=True, verbose_name="Data Saída"),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="ph_agua",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="pH água"
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="ph_cacl2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="pH Cacl2",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="ph_kcl",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="pH Kcl",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="area",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Área"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="codigo",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Código Cliente"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="contato",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Contato"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="municipio",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Município"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="observacoes",
            field=models.TextField(blank=True, null=True, verbose_name="Obs"),
        ),
    ]
