# Generated by Django 5.2.11 on 2026-02-19 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_rename_ctc_potencial_analisesolo_t_maiusculo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analisesolo",
            name="ca_k",
        ),
        migrations.RemoveField(
            model_name="analisesolo",
            name="mg_k",
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="T_maiusculo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="T (CTC pH 7.0)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="V",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=6,
                null=True,
                verbose_name="V% (Saturação por Bases)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="al",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, verbose_name="Alumínio (Al3+)"
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="areia",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Areia %",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="argila",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Argila %",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="b",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Boro (B)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="c_org",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="C-org",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="ca",
            field=models.DecimalField(
                decimal_places=4, max_digits=12, verbose_name="Cálcio (Ca)"
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="ca_mg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Relação Ca/Mg",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analises",
                to="database.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="cu",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Cobre (Cu)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="fe",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Ferro (Fe)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="h_al",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, verbose_name="Acidez Potencial (H+Al)"
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="k",
            field=models.DecimalField(
                decimal_places=4, max_digits=12, verbose_name="Potássio (K)"
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="m",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=6,
                null=True,
                verbose_name="m% (Saturação por Al)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="mg",
            field=models.DecimalField(
                decimal_places=4, max_digits=12, verbose_name="Magnésio (Mg)"
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="mn",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Manganês (Mn)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="mo",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, verbose_name="Matéria Orgânica"
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="na",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Sódio (Na)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="p_m",
            field=models.DecimalField(
                decimal_places=4, max_digits=12, verbose_name="P_M (Mehlich)"
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="p_r",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="P_R (Resina)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="p_rem",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="P-rem",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="ph_agua",
            field=models.DecimalField(
                decimal_places=4, max_digits=8, verbose_name="pH água"
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="ph_cacl2",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=8,
                null=True,
                verbose_name="pH CaCl2",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="ph_kcl",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=8,
                null=True,
                verbose_name="pH KCl",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="s",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Enxofre (S)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="sb",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="SB",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="silte",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Silte %",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="t",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="t (CTC Efetiva)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="zn",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Zinco (Zn)",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
