# Generated by Django 5.2.11 on 2026-02-20 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0003_remove_analisesolo_ca_k_remove_analisesolo_mg_k_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BateriaCalibracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Calibração"
                    ),
                ),
                (
                    "equipamento",
                    models.CharField(
                        choices=[
                            ("AA", "Absorção Atômica"),
                            ("FC", "Fotômetro de Chama"),
                            ("ES", "Espectrofotômetro"),
                            ("TI", "Titulação"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "elemento",
                    models.CharField(
                        choices=[
                            ("Ca", "Cálcio"),
                            ("Mg", "Magnésio"),
                            ("Cu", "Cobre"),
                            ("Fe", "Ferro"),
                            ("Mn", "Manganês"),
                            ("Zn", "Zinco"),
                            ("K", "Potássio"),
                            ("Na", "Sódio"),
                            ("P_M", "Fósforo (Mehlich)"),
                            ("P_R", "Fósforo (Resina)"),
                            ("P_rem", "Fósforo Remanescente"),
                            ("S", "Enxofre"),
                            ("B", "Boro"),
                            ("Al", "Alumínio"),
                            ("H_Al", "Acidez Potencial"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "coeficiente_angular_a",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=15,
                        null=True,
                        verbose_name="Inclinação (b)",
                    ),
                ),
                (
                    "coeficiente_linear_b",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=15,
                        null=True,
                        verbose_name="Intercepto (a)",
                    ),
                ),
                (
                    "r_quadrado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=7,
                        null=True,
                        verbose_name="R²",
                    ),
                ),
                (
                    "leitura_branco",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True, verbose_name="Bateria Ativa no Dia?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bateria de Calibração",
                "verbose_name_plural": "Baterias de Calibração",
            },
        ),
        migrations.CreateModel(
            name="LeituraEquipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leitura_bruta", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "analise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leituras_brutas",
                        to="database.analisesolo",
                    ),
                ),
                (
                    "bateria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leituras",
                        to="database.bateriacalibracao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leitura de Equipamento",
                "verbose_name_plural": "Leituras de Equipamento",
            },
        ),
    ]
