# Generated by Django 5.2.11 on 2026-02-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0004_bateriacalibracao_leituraequipamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="analisesolo",
            name="ca_k",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Relação Ca/K",
            ),
        ),
        migrations.AddField(
            model_name="analisesolo",
            name="mg_k",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Relação Mg/K",
            ),
        ),
    ]
