# Generated by Django 5.2.11 on 2026-02-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0005_analisesolo_ca_k_analisesolo_mg_k"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analisesolo",
            name="al",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Alumínio (Al3+)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="ca",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Cálcio (Ca)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="h_al",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Acidez Potencial (H+Al)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="k",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Potássio (K)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="mg",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Magnésio (Mg)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="mo",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Matéria Orgânica",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="p_m",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="P_M (Mehlich)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="ph_agua",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=8,
                null=True,
                verbose_name="pH água",
            ),
        ),
    ]
