# Generated by Django 5.2.11 on 2026-02-20 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0006_alter_analisesolo_al_alter_analisesolo_ca_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PontoCalibracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concentracao",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        verbose_name="Concentração (Padrão)",
                    ),
                ),
                (
                    "absorvancia",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        verbose_name="Leitura (Absorbância)",
                    ),
                ),
                (
                    "bateria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pontos",
                        to="database.bateriacalibracao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ponto de Calibração",
                "verbose_name_plural": "Pontos de Calibração",
                "ordering": ["concentracao"],
            },
        ),
    ]
