# Generated by Django 5.2.11 on 2026-02-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0007_pontocalibracao"),
    ]

    operations = [
        migrations.AddField(
            model_name="leituraequipamento",
            name="fator_diluicao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Deixe vazio para usar o padrão (10x Ca/Mg, 1x Demais)",
                max_digits=6,
                null=True,
                verbose_name="Fator de Diluição (Opcional)",
            ),
        ),
        migrations.AlterField(
            model_name="bateriacalibracao",
            name="elemento",
            field=models.CharField(
                choices=[
                    ("Ca", "Cálcio"),
                    ("Mg", "Magnésio"),
                    ("Cu", "Cobre"),
                    ("Fe", "Ferro"),
                    ("Mn", "Manganês"),
                    ("Zn", "Zinco"),
                    ("K", "Potássio"),
                    ("Na", "Sódio"),
                    ("P_M", "Fósforo (Mehlich)"),
                    ("P_R", "Fósforo (Resina)"),
                    ("P_rem", "Fósforo Remanescente"),
                    ("S", "Enxofre"),
                    ("B", "Boro"),
                    ("Al", "Alumínio"),
                    ("H_Al", "Acidez Potencial"),
                    ("ph_agua", "pH em Água"),
                    ("ph_cacl2", "pH em CaCl2"),
                    ("ph_kcl", "pH em KCl"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="bateriacalibracao",
            name="equipamento",
            field=models.CharField(
                choices=[
                    ("AA", "Absorção Atômica"),
                    ("FC", "Fotômetro de Chama"),
                    ("ES", "Espectrofotômetro"),
                    ("TI", "Titulação"),
                    ("PH", "Phagâmetro"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="bateriacalibracao",
            name="leitura_branco",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Obrigatório para Absorção Atômica (AA). Ignorado no Fotômetro (FC) e Phagâmetro (PH).",
                max_digits=10,
                null=True,
                verbose_name="Leitura do Branco",
            ),
        ),
    ]
