# Generated by Django 5.2.11 on 2026-02-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0008_leituraequipamento_fator_diluicao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bateriacalibracao",
            name="elemento",
            field=models.CharField(
                choices=[
                    ("Ca", "Cálcio"),
                    ("Mg", "Magnésio"),
                    ("Cu", "Cobre"),
                    ("Fe", "Ferro"),
                    ("Mn", "Manganês"),
                    ("Zn", "Zinco"),
                    ("K", "Potássio"),
                    ("Na", "Sódio"),
                    ("P_M", "Fósforo (Mehlich)"),
                    ("P_R", "Fósforo (Resina)"),
                    ("P_rem", "Fósforo Remanescente"),
                    ("S", "Enxofre"),
                    ("B", "Boro"),
                    ("Al", "Alumínio"),
                    ("H_Al", "Acidez Potencial"),
                    ("ph_agua", "pH em Água"),
                    ("ph_cacl2", "pH em CaCl2"),
                    ("ph_kcl", "pH em KCl"),
                    ("MO", "Matéria Orgânica"),
                ],
                max_length=15,
            ),
        ),
    ]
