# Generated by Django 5.2.11 on 2026-02-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0009_alter_bateriacalibracao_elemento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pontocalibracao",
            name="absorvancia",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=10,
                verbose_name="Leitura Bruta (Transm % ou Abs)",
            ),
        ),
    ]
