# Generated by Django 5.2.11 on 2026-02-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0010_alter_pontocalibracao_absorvancia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leituraequipamento",
            name="leitura_bruta",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Siga a instrução no nome da bateria selecionada ao lado.",
                max_digits=10,
                verbose_name="Leitura do Visor",
            ),
        ),
    ]
