# Generated by Django 5.2.11 on 2026-02-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0011_alter_leituraequipamento_leitura_bruta"),
    ]

    operations = [
        migrations.AddField(
            model_name="bateriacalibracao",
            name="volume_extrator",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ex: 50.00 para maioria ou 25.00 para Enxofre",
                max_digits=10,
                null=True,
                verbose_name="Volume de Extrator (ml)",
            ),
        ),
        migrations.AddField(
            model_name="bateriacalibracao",
            name="volume_solo",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Ex: 0.005 para Ca/Mg/P ou 0.010 para Enxofre",
                max_digits=10,
                null=True,
                verbose_name="Volume de Solo (cm³)",
            ),
        ),
    ]
