# Generated by Django 5.2.11 on 2026-02-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0012_bateriacalibracao_volume_extrator_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leituraequipamento",
            options={},
        ),
        migrations.AlterField(
            model_name="bateriacalibracao",
            name="leitura_branco",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Obrigatório para AA. Ignorado no FC e PH.",
                max_digits=10,
                null=True,
                verbose_name="Leitura do Branco",
            ),
        ),
        migrations.AlterField(
            model_name="bateriacalibracao",
            name="volume_extrator",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ex: 50.00 para maioria ou 25.00 para S",
                max_digits=10,
                null=True,
                verbose_name="Volume de Extrator (ml)",
            ),
        ),
        migrations.AlterField(
            model_name="bateriacalibracao",
            name="volume_solo",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Ex: 0.005 para Ca/Mg/P ou 0.010 para S",
                max_digits=10,
                null=True,
                verbose_name="Volume de Solo (cm³)",
            ),
        ),
        migrations.AlterField(
            model_name="leituraequipamento",
            name="fator_diluicao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Vazio = Padrão.",
                max_digits=6,
                null=True,
                verbose_name="Fator de Diluição (Opcional)",
            ),
        ),
        migrations.AlterField(
            model_name="leituraequipamento",
            name="leitura_bruta",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Siga a instrução no nome da bateria selecionada.",
                max_digits=10,
                verbose_name="Leitura do Visor",
            ),
        ),
    ]
