# Generated by Django 5.2.11 on 2026-02-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0013_alter_leituraequipamento_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bateriacalibracao",
            name="leitura_branco",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Leitura do Branco",
            ),
        ),
        migrations.AlterField(
            model_name="bateriacalibracao",
            name="volume_extrator",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Volume de Extrator (ml)",
            ),
        ),
        migrations.AlterField(
            model_name="bateriacalibracao",
            name="volume_solo",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Volume de Solo (cm³)",
            ),
        ),
        migrations.AlterField(
            model_name="leituraequipamento",
            name="fator_diluicao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Fator de Diluição (Opcional)",
            ),
        ),
        migrations.AlterField(
            model_name="leituraequipamento",
            name="leitura_bruta",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, verbose_name="Leitura do Visor"
            ),
        ),
    ]
