# Generated by Django 5.2.11 on 2026-02-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0014_alter_bateriacalibracao_leitura_branco_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analisesolo",
            options={
                "verbose_name": "Analise de Solo",
                "verbose_name_plural": "Analises de Solo",
            },
        ),
        migrations.AlterModelOptions(
            name="bateriacalibracao",
            options={
                "verbose_name": "Bateria de Calibracao",
                "verbose_name_plural": "Baterias de Calibracao",
            },
        ),
        migrations.AlterModelOptions(
            name="pontocalibracao",
            options={
                "ordering": ["concentracao"],
                "verbose_name": "Ponto de Calibracao",
                "verbose_name_plural": "Pontos de Calibracao",
            },
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="T_maiusculo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="T (CTC pH 7.0)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="V",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=0,
                max_digits=6,
                null=True,
                verbose_name="V% (Saturacao por Bases)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="al",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Aluminio (Al3+)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="areia",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=6,
                null=True,
                verbose_name="Areia %",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="argila",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=6,
                null=True,
                verbose_name="Argila %",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="b",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Boro (B)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="c_org",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=8,
                null=True,
                verbose_name="C-org",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="ca",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Calcio (Ca)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="ca_k",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=8,
                null=True,
                verbose_name="Relacao Ca/K",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="ca_mg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=8,
                null=True,
                verbose_name="Relacao Ca/Mg",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="cu",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Cobre (Cu)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="data_saida",
            field=models.DateField(blank=True, null=True, verbose_name="Data Saida"),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="fe",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Ferro (Fe)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="h_al",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Acidez Potencial (H+Al)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="k",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Potassio (K)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="m",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=0,
                max_digits=6,
                null=True,
                verbose_name="m% (Saturacao por Al)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="mg",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Magnesio (Mg)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="mg_k",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=8,
                null=True,
                verbose_name="Relacao Mg/K",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="mn",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Manganes (Mn)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="mo",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Materia Organica",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="na",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Sodio (Na)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="p_m",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="P_M (Mehlich)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="p_r",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="P_R (Resina)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="p_rem",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="P-rem",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="ph_agua",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=8,
                null=True,
                verbose_name="pH agua",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="ph_cacl2",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=8,
                null=True,
                verbose_name="pH CaCl2",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="ph_kcl",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=8,
                null=True,
                verbose_name="pH KCl",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="s",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Enxofre (S)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="sb",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="SB",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="silte",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=6,
                null=True,
                verbose_name="Silte %",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="t",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="t (CTC Efetiva)",
            ),
        ),
        migrations.AlterField(
            model_name="analisesolo",
            name="zn",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Zinco (Zn)",
            ),
        ),
        migrations.AlterField(
            model_name="bateriacalibracao",
            name="coeficiente_angular_a",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=15,
                null=True,
                verbose_name="Inclinacao (b)",
            ),
        ),
        migrations.AlterField(
            model_name="bateriacalibracao",
            name="data_criacao",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data da Calibracao"
            ),
        ),
        migrations.AlterField(
            model_name="bateriacalibracao",
            name="elemento",
            field=models.CharField(
                choices=[
                    ("Ca", "Calcio"),
                    ("Mg", "Magnesio"),
                    ("Cu", "Cobre"),
                    ("Fe", "Ferro"),
                    ("Mn", "Manganes"),
                    ("Zn", "Zinco"),
                    ("K", "Potassio"),
                    ("Na", "Sodio"),
                    ("P_M", "Fosforo (Mehlich)"),
                    ("P_R", "Fosforo (Resina)"),
                    ("P_rem", "Fosforo Remanescente"),
                    ("S", "Enxofre"),
                    ("B", "Boro"),
                    ("Al", "Aluminio"),
                    ("H_Al", "Acidez Potencial"),
                    ("ph_agua", "pH em Agua"),
                    ("ph_cacl2", "pH em CaCl2"),
                    ("ph_kcl", "pH em KCl"),
                    ("MO", "Materia Organica"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="bateriacalibracao",
            name="equipamento",
            field=models.CharField(
                choices=[
                    ("AA", "Absorcao Atomica"),
                    ("FC", "Fotometro de Chama"),
                    ("ES", "Espectrofotometro"),
                    ("TI", "Titulacao"),
                    ("PH", "Phagametro"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="bateriacalibracao",
            name="r_quadrado",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=7, null=True, verbose_name="R2"
            ),
        ),
        migrations.AlterField(
            model_name="bateriacalibracao",
            name="volume_solo",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Volume de Solo (cm3)",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="area",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Area"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="codigo",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Codigo Cliente"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="municipio",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Municipio"
            ),
        ),
        migrations.AlterField(
            model_name="leituraequipamento",
            name="fator_diluicao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Fator de Diluicao (Opcional)",
            ),
        ),
        migrations.AlterField(
            model_name="pontocalibracao",
            name="concentracao",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, verbose_name="Concentracao (Padrao)"
            ),
        ),
    ]
