# Generated by Django 5.2.11 on 2026-04-08 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_laudo_data_saida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contato',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='data_emissao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Entrada'),
        ),
    ]
