# Generated by Django 5.2.11 on 2026-08-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_replace_contato_with_telefone_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analisesolo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='analisesolo',
            name='n_lab',
            field=models.CharField(max_length=50, unique=True, verbose_name='N Lab'),
        ),
    ]
