# Generated by Django 5.2.11 on 2026-08-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_unique_leitura_por_analise_bateria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bateriacalibracao',
            name='ativo',
        ),
    ]
