# Generated by Django 5.2.11 on 2026-08-12 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_remove_ativo_bateriacalibracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Conjunto')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conjunto de Padroes',
                'verbose_name_plural': 'Conjuntos de Padroes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PadraoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('padrao_a', 'Padrão A'), ('padrao_b', 'Padrão B'), ('p_labas_a', 'P. Labas A'), ('p_labas_b', 'P. Labas B')], max_length=20, verbose_name='Tipo')),
                ('ph_agua', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='pH agua')),
                ('ph_cacl2', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='pH CaCl2')),
                ('ph_kcl', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='pH KCl')),
                ('p_m', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='P_M (Mehlich)')),
                ('p_r', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='P_R (Resina)')),
                ('p_rem', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='P-rem')),
                ('mo', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Materia Organica')),
                ('s', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Enxofre (S)')),
                ('b', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Boro (B)')),
                ('k', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Potassio (K)')),
                ('na', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Sodio (Na)')),
                ('ca', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Calcio (Ca)')),
                ('mg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Magnesio (Mg)')),
                ('cu', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Cobre (Cu)')),
                ('fe', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Ferro (Fe)')),
                ('mn', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Manganes (Mn)')),
                ('zn', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Zinco (Zn)')),
                ('al', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Aluminio (Al3+)')),
                ('h_al', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Acidez Potencial (H+Al)')),
                ('sb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='SB')),
                ('t', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='t (CTC Efetiva)')),
                ('T_maiusculo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='T (CTC pH 7.0)')),
                ('V', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='V%')),
                ('m', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='m%')),
                ('ca_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ca/Mg')),
                ('ca_k', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ca/K')),
                ('mg_k', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Mg/K')),
                ('c_org', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='C-org')),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padroes', to='database.conjuntopadrao')),
            ],
            options={
                'verbose_name': 'Padrao do Laboratorio',
                'verbose_name_plural': 'Padroes do Laboratorio',
                'ordering': ['tipo'],
                'constraints': [models.UniqueConstraint(fields=('conjunto', 'tipo'), name='unique_tipo_por_conjunto')],
            },
        ),
    ]
